#!/usr/bin/env python3
"""Regenerate sitemap.xml from the page list below.

  python3 tools/build-sitemap.py

lastmod comes from git, not from filesystem mtime: a fresh clone or a checkout
rewrites mtimes, which would hand crawlers a sitemap claiming every page changed
today. The commit date is the honest answer.

NOTE the site is pre-launch. Every page carries <meta name="robots"
"noindex, nofollow"> and robots.txt is Disallow: /, so nothing here is crawled
yet. This exists so that sign-off is a one-line change, not a project.
"""
import subprocess, datetime, sys, os

BASE = "https://www.tienyan.com"

# priority/changefreq are hints only. Google ignores both; Bing and several AI
# crawlers still read them, and they cost nothing to state.
PAGES = [
    ("",                 "1.0", "monthly"),
    ("our-story.html",   "0.8", "yearly"),
    ("partnership.html", "0.8", "yearly"),
    ("products.html",    "0.9", "monthly"),
    ("contact.html",     "0.7", "yearly"),
    ("privacy.html",     "0.2", "yearly"),
    ("terms.html",       "0.2", "yearly"),
    ("cookies.html",     "0.2", "yearly"),
]

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def lastmod(path):
    f = path or "index.html"
    out = subprocess.run(["git", "log", "-1", "--format=%cs", "--", f],
                         capture_output=True, text=True, cwd=ROOT).stdout.strip()
    return out or datetime.date.today().isoformat()


def main():
    missing = [p for p, _, _ in PAGES if p and not os.path.exists(os.path.join(ROOT, p))]
    if missing:
        print("Refusing to write a sitemap listing pages that do not exist:", file=sys.stderr)
        for m in missing:
            print(f"  - {m}", file=sys.stderr)
        return 1

    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<!-- Generated by tools/build-sitemap.py. Regenerate after adding a page. -->',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for path, prio, freq in PAGES:
        lines += ['  <url>',
                  f'    <loc>{BASE}/{path}</loc>',
                  f'    <lastmod>{lastmod(path)}</lastmod>',
                  f'    <changefreq>{freq}</changefreq>',
                  f'    <priority>{prio}</priority>',
                  '  </url>']
    lines.append('</urlset>')

    with open(os.path.join(ROOT, "sitemap.xml"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"sitemap.xml written with {len(PAGES)} URLs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
